create database customer_behavior;
use customer_behavior;
select * from customer;

-- 1. What is the total revenue generated by male vs. female customer.
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- 2. Which customer used discount but still spend more than the average purchase amount.
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount)
from customer);

-- 3. Which are the top 5 products with the highest average review rating.
select item_purchased, round(avg(review_rating),1) as "Average product Rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

-- 4. Compare the average purchase amounts between standard and express shipping.
select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- 5. Do subscribed customer spend more? compare average apend and total revenue between subscribers or non-subscribers.
select subscription_status, count(customer_id) AS "Total Customers",
round(avg(purchase_amount),2) AS "AVG Spend",
round(sum(purchase_amount),2) AS "Total Revenue"
from customer
group by subscription_status
order by "Total Revenue", "AVG Spend";

-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100,2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7. Segment customers into New, REturning, Loyal based on their total number of previous purchases, and show the each segments.
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases  = 1 then 'New'
    when previous_purchases = 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
GROUP BY customer_segment;

-- 8. What are the top 3 most purchased products within each categpty?
with item_counts as (
select category, item_purchased,
count(customer_id) as Total_orders,
row_number() over(partition by category order by count(customer_id) desc) as Item_RAnk
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subcribe.
select subscription_status, count(customer_id) AS Repeat_Buyer
from customer
where previous_purchases > 5
group by subscription_status;

-- 10. What is the revenue contribution of each group.
select age_group, sum(purchase_amount) AS Total_revenue
from customer
group by age_group
order by Total_revenue desc;